[book]
authors = ["Radxa Limited"]
language = "en"
multilingual = false
src = "src"
title = "Radxa Documentation"

[output.html]
git-repository-url = "https://github.com/radxa-doc/radxa-doc.github.io/tree/main"
edit-url-template = "https://github.com/radxa-doc/radxa-doc.github.io/edit/main/{path}"